### ISSUE TITLE
Android and iOS Min Version

### ISSUE THREAD

**Issue by nespapu** [Crypho/com.crypho.plugins.securestorage#6]
Hi,

Congrats for the plugin! We are finding it very useful :)

Can you tell us which is the min version for Android and iOS this plugin supports?

EDIT:

Ok, I see in your code that min version for Android is API 19, which is quite new, so lot of devices are left out for the use of this plugin. is this min version mandatory?

EDIT2:

I've tried to replace the min version the plugin is setting up to the app with:

        <gap:config-file platform="android" parent="/manifest" mode="replace">
             <uses-sdk   android:minSdkVersion="14" android:targetSdkVersion="14"/>
       </gap:config-file>

But I have no luck. Do you know any other way to overcome this problem?

EDIT3:

I have also tried this, but with the same result :(

        <preference name="android-targetSdkVersion" value="14" />
        <preference name="android-minSdkVersion" value="14" />

Thanks

**Comment by ggozad** [comment]
Sorry for the late reply, had accidentally unwatched the repo :)
No, 19 is really required for some of the android primitives we use.
