### ISSUE TITLE
Extra uses-sdk entry getting added to AndroidManifest.xml

### ISSUE THREAD

**Issue by mattalco** [Crypho/com.crypho.plugins.securestorage#8]
Hello,

It appears this entry in your plugin.xml file is causing ionic to append an extra uses-sdk entry in the AndroidManifest.xml file.

        <config-file target="AndroidManifest.xml" parent="/manifest">
            <uses-sdk   android:minSdkVersion="19" android:targetSdkVersion="19"/>
        </config-file>

After performing an ionic build, we end up with this in our manifest file which causes all android builds to fail since there's a project level version support configuration and the one this plugin injects. 

uses-sdk android:minSdkVersion="19" android:targetSdkVersion="22"
uses-sdk android:minSdkVersion="19" android:targetSdkVersion="19"

Is there another way to document this dependency to prevent this the injection?

**Comment by ggozad** [comment]
Hey sorry for the very late reply, I had unwatched the repo by accident and never got to see this.
I am not using ionic, but will be happy to accept a PR that fixes it for you. Can you try keeping the minimum sdk directive and remove the target and let me know if this fixes it for you?

**Comment by ggozad** [comment]
Done in #10

**Comment by mattalco** [comment]
Thank you :)
