### ISSUE TITLE
Why is the extra complexity of the AES encryption in Android

### ISSUE THREAD

**Issue by froyke** [Crypho/com.crypho.plugins.securestorage#9]
Hi,
Is there a reason for adding the extra AES encryption (on Adnroid)?
As I see it, the actual values could be encrypted/decrypted using the RSA one (from the keystore) - removing extra AES enc/dec cycle and reducing code complexity.

Thanks for your reply and for this useful library.

**Comment by ggozad** [comment]
Hey!
RSA can encrypt payloads <= to its key size. Hence we use AES for encryption and then RSA to encrypt the key.
